Create translation-guide.md
ts-zh-docs/TypeScript-Website pull request #10
Opened 2024-01-25 02:34 UTC by hanyujie2002

The translation guide is based on that of MDN https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md

Relates to https://github.com/ts-zh-docs/community/issues/5

2024-01-25 02:43 UTC, hanyujie2002 commented on docs/translation-guide.md
> +
```suggestion
- `permalink`（必须）：为与网页 URL 相关的元数据
- `oneline`（必须）：用一句话简要介绍文章内容
```

2024-01-25 02:43 UTC, hanyujie2002 commented on docs/translation-guide.md
> +- `layout`（必须）
```suggestion
- `layout`（必须）：目前统一为 `docs`
```

2024-01-25 02:43 UTC, hanyujie2002 commented on docs/translation-guide.md
> +// todo
```suggestion
title: 标题
layout: docs
permalink: /docs/handbook/2/example.html
oneline: "对文章内容的简要介绍"
```

2024-01-25 02:43 UTC, hanyujie2002 commented on docs/translation-guide.md
> +
```suggestion
```

2024-01-25 02:43 UTC, hanyujie2002 commented on docs/translation-guide.md
> +```
```suggestion
```

2024-01-25 02:44 UTC, hanyujie2002 commented on docs/translation-guide.md
> +- `oneline`（必须）：用一句话简要介绍文章内容
```suggestion
- `oneline`（必须）：用一句话简要介绍文章内容

```

2024-01-25 02:44 UTC, hanyujie2002 commented on docs/translation-guide.md
> +
```suggestion
```

2024-01-25 05:49 UTC, awxiaoxian2020 requested changes

2024-01-25 05:49 UTC, awxiaoxian2020 commented on docs/translation-guide.md
> +我们无需将“you”翻译为“您”，在文档正文部分的翻译中，请统一使用“你”。
My preference.
cc: @hanyujie2002 @Jeffzholy @EnochGao 
```suggestion
我们无需将“you”翻译为“您”，在文档正文部分的翻译中，请统一使用“你”。且在中文技术文档中，一般语气风格较为客观，在交互性不是很强的情况下，可以考虑删去“你”这样的主语，显得更符合中文表达习惯。
```

2024-01-25 05:49 UTC, awxiaoxian2020 commented on docs/translation-guide.md
> +[如何使用 markdown 来撰写文档]: https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN
187 188 不建议保留

2024-01-25 07:22 UTC, hanyujie2002 commented on docs/translation-guide.md
> +[运行实例]: https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Page_structures/Live_samples
```suggestion
```

2024-01-25 07:23 UTC, hanyujie2002 commented on docs/translation-guide.md
> +
```suggestion
```

2024-01-26 13:06 UTC, awxiaoxian2020 requested changes

2024-01-26 13:06 UTC, awxiaoxian2020 commented on docs/translation-guide.md
> +> 若你对本文档使用的 Markdown 格式不熟悉，请参阅[如何使用 markdown 来撰写文档][]。
here

2024-01-27 07:26 UTC, hanyujie2002 commented on docs/translation-guide.md
> +> 若你对本文档使用的 Markdown 格式不熟悉，请参阅[如何使用 markdown 来撰写文档][]。
```suggestion
> 若你对本文档使用的 Markdown 格式不熟悉，请参阅[如何使用 markdown 来撰写文档][https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN]。
```

2024-01-29 02:38 UTC, awxiaoxian2020 commented
We should move these docs to `zh` repo. But now, let's merge it.

2024-01-29 02:40 UTC, merged